### PR TITLE
nav: Change "Title Case" to "Sentence case"

### PR DESCRIPTION
**Pull request by garrett**
Fix for https://github.com/cockpit-project/cockpit/issues/17590

### CODE REVIEW

**Review by marusak — DISMISSED** [review]
Thanks!

**Comment by martinpitt** [comment]
We need to bump testlib to fix [these](https://cockpit-logs.us-east-1.linodeobjects.com/pull-776-20220725-090926-859f6273-centos-8-stream/log.html#47-2) [kinds of](https://cockpit-logs.us-east-1.linodeobjects.com/pull-776-20220725-090926-859f6273-ubuntu-2204/log.html) [failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-776-20220725-090926-859f6273-ubuntu-stable/log.html). PR coming.

**Comment by martinpitt** [comment]
Sent PR #777 for better flight experience :man_pilot: , let's re-run after that landed.

**Review by martinpitt — APPROVED** [review]
Rebased after landing the new test API. Letting tests run again, I hope they are more stable now.

**Pull request merged**
