### PR TITLE
machines: fix oops because of react updating recursively too many times

### PR DESCRIPTION
**Pull request by KKoukiou**
* [x] blocked on https://github.com/patternfly/patternfly-react/pull/5973

Relevant to: https://bugzilla.redhat.com/show_bug.cgi?id=1977554

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Heh, indeed that felt a bit like redux without redux :grin: Nice job on the test case!

**Comment by KKoukiou** [comment]
LOl seems that my new test cought the issue that I did not fix :P

**Comment by martinpitt** [comment]
Nice to see that [TF rawhide tests](http://artifacts.dev.testing-farm.io/d82898bb-3fe1-40d0-85ed-cfe18ac77c0f/) are running again in general. `TestMachinesNICs.testNICAdd` failed [screenshot](http://artifacts.dev.testing-farm.io/d82898bb-3fe1-40d0-85ed-cfe18ac77c0f/work-all4jAOJA/plans/all/discover/default/tests/TestMachinesNICs-testNICAdd-fedora-35-localhost-22-FAIL.png) due to "vmSubTest1 does not exist on system connection", which points to a race in the test?

**Review by martinpitt — APPROVED** [review]
Thanks! (Fun test case!)

**Pull request merged**
