### PR TITLE
Move to webpack 5

### PR DESCRIPTION
**Pull request by martinpitt**
Cherry-picked from starter-kit commit c52136c0514.

----

 - [x] Builds on top of PR #87 
 - [x] Consider if the Table warnings are important enough to block: https://github.com/patternfly/patternfly-react/issues/5644
 - [x] Fix/work around build failures with `ip` npm package
 
This currently spits out 23 warnings of this form:
```
WARNING in ./node_modules/patternfly-react/dist/esm/components/Table/Table.js 21:0-31
export 'actionHeaderCellFormatter' (imported as 'Table') was not found in 'reactabular-table' (possible exports: Body, BodyRow, Header, Provider, __esModule, columnsAreEqual, evaluateFormatters, evaluateTransforms, mergeProps, resolveRowKey)
```

This feels like a PatternFly bug. It still seems to work anyway, let's see what CI says.

### CODE REVIEW

**Comment by martinpitt** [comment]
I tried to rebase this locally, as most of the prerequisites already landed. But now this fails on the recently added [ip npm package(https://www.npmjs.com/package/ip):
```
ERROR in ./node_modules/ip/lib/ip.js 4:13-37
Module not found: Error: Can't resolve 'buffer' in '/var/home/martin/upstream/cockpit-machines/node_modules/ip/lib'

ERROR in ./node_modules/ip/lib/ip.js 5:9-22
Module not found: Error: Can't resolve 'os' in '/var/home/martin/upstream/cockpit-machines/node_modules/ip/lib'
```

**Comment by KKoukiou** [comment]
@martinpitt regarding you warning from th patternfly-react repository. patternfly-react is  the old PF3 module. We don't use the table from there, so any warning related to Table in patternfly-react is defiintely a non blocker.

**Comment by martinpitt** [comment]
@KKoukiou : Right, and the [next PF version may even fix the warnings](https://github.com/patternfly/patternfly-react/pull/5645). But they'd still appear during package build, and make stuff hard to read. Anyway, need to get this to work again first, with the newly introduced (and rather unmaintained) `ip` module.

**Comment by KKoukiou** [comment]
@martinpitt I just force pushed with the remaining fixes - hope that's fine. Will approve it - but since I modified it - will leave it up to you to merge.

**Review by KKoukiou — DISMISSED** [review]

**Comment by KKoukiou** [comment]
> @martinpitt I just force pushed with the remaining fixes - hope that's fine. Will approve it - but since I modified it - will leave it up to you to merge.

not yet ready aparently - some build failures still which did not appear locally.

**Comment by KKoukiou** [comment]
Build-dist is failing with FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory. We need the NODE_OPTIONS hack.

**Comment by KKoukiou** [comment]
Update: updating the terser plugin fixed the out of memory issues.

**Comment by martinpitt** [comment]
Sounds similar to https://github.com/cockpit-project/cockpit-podman/pull/724 , which also renamed LICENSE.txt to .gz?

**Comment by KKoukiou** [comment]
The pixel test failures seem real.

**Review by KKoukiou — APPROVED** [review]

**Comment by martinpitt** [comment]
FTR, LGTM :+1: Thanks @KKoukiou for the clever fixes! (I hope we can clean this up soon)

**Comment by martinpitt** [comment]
Yay, green! (aside from the known rawhide FUBAR)

**Pull request merged**
