### PR TITLE
DBG - let me see the flake!

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
@martinpitt, this is for my own amusement only. I want to see whether https://github.com/cockpit-project/cockpit-machines/pull/1539 can maybe be reverted, etc.

**Comment by mvollmer** [comment]
It's not happening...

**Comment by martinpitt** [comment]
@mvollmer: It totally is happening, see [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093346-ubuntu-stable/log.html), [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093346-ubuntu-2204/log.html), [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093347-fedora-39-firefox/log.html), [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093346-debian-testing/log.html), or [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093346-debian-testing/log.html) run. The only thing that "saved" you were the automatic retries -- presumably because the changes and reverts somehow cancel out to not make these tests count as "affected" any more, or our retry logic is screwed up?

 I could imagine that the debounce hack replaces commit 72645805086ce05e09a5d2f6c7e77316e44aa2ff (going back to internal state management), but I can't for the life of me believe that testDetachDisk() would just work without any hacks -- it was failing [like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1510-9426096c-20240320-161159-fedora-39/log.html#29-1) all the time in ~ 60% of runs, even locally. I used test amplification and "all 3x affected runs must pass" in my PRs.

**Comment by mvollmer** [comment]
> It totally is happening, see [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093346-ubuntu-stable/log.html), [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093346-ubuntu-2204/log.html), [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093347-fedora-39-firefox/log.html), [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093346-debian-testing/log.html), or [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1552-e682d2aa-20240411-093346-debian-testing/log.html) run.

Ah, thansk, I wasn't looking closely enough.

**Pull request closed without merging**
