### PR TITLE
test: check more abnormal scenarios on the adding file system dialog 

### PR DESCRIPTION
**Pull request by yunmingyang**

### CODE REVIEW

**Comment by martinpitt** [comment]
This fails `TestMachinesFilesystems.testBasicSystemConnection` everywhere. The commit message is also hard to understand and too long. Perhaps "test: separate helper checks for fs add dialog"?

**Comment by yunmingyang** [comment]
Thanks, I will check and reduce the length of the commit message

**Comment by martinpitt** [comment]
@yunmingyang This is still draft -- do you still want to work on this, or ready for review?

**Comment by yunmingyang** [comment]
Ah, yeah, I think it's ready now

**Review by martinpitt — APPROVED** [review]
Sorry that this slipped through the cracks! Looks good to me. I pushed a rebase to make sure it still works, and will land ASAP.

**Pull request merged**
