### PR TITLE
Delete storage files also when the  VM is shut off

### LINKED ISSUE #598: Not properly deleting a VM
Clone VM -> test
Delete test VM -> deletes it from the UI
However the image file still exists
```
# ls -la /var/lib/libvirt/images/test.qcow2
-rw------- 1 root root 4783800320 Feb 27 08:56 /var/lib/libvirt/images/test.qcow2
```

```
ii  cockpit                               261-1~bpo20.04.1                      all          Web Console for Linux servers
ii  cockpit-bridge                        261-1~bpo20.04.1                      amd64        Cockpit bridge server-side component
ii  cockpit-machines                      260-1~bpo20.04.1                      all          Cockpit user interface for virtual machines
ii  cockpit-networkmanager                261-1~bpo20.04.1                      all          Cockpit user interface for networking
ii  cockpit-packagekit                    261-1~bpo20.04.1                      all          Cockpit user interface for packages
ii  cockpit-pcp                           261-1~bpo20.04.1                      amd64        Cockpit PCP integration
ii  cockpit-storaged                      261-1~bpo20.04.1                      all          Cockpit user interface for storage
ii  cockpit-system                        261-1~bpo20.04.1                      all          Cockpit admin interface for a system
ii  cockpit-ws                            261-1~bpo20.04.1                      amd64        Cockpit Web Service
```

### PR DESCRIPTION
**Pull request by KKoukiou**
Commit https://github.com/cockpit-project/cockpit-machines/commit/ed073898e
broke this functionality.

Fixes #598

### CODE REVIEW

**Comment by KKoukiou** [comment]
hmm let me add a test as well.

**Comment by martinpitt** [comment]
`TestMachinesLifecycle.testDelete` still [fails on c9s](https://artifacts.dev.testing-farm.io/e41a23c3-f822-472c-98c1-f743e8b04768/)

**Comment by KKoukiou** [comment]
> `TestMachinesLifecycle.testDelete` still [fails on c9s](https://artifacts.dev.testing-farm.io/e41a23c3-f822-472c-98c1-f743e8b04768/)

retrying once in CI before starting to debug it.

**Review by skobyda — DISMISSED** [review]
Thanks. Code looks good and the additional test also looks great :) . Let's make the tests green and it's good to me.

**Comment by martinpitt** [comment]
[debian-testing failure](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-601-20220228-124842-a49fa3fe-debian-stable/log.html#70-1) happened earlier on already, I can't reproduce that locally. Retrying.

I tried to reproduce the [c8s failure](https://artifacts.dev.testing-farm.io/246b3cdc-7f7e-46a1-b648-29855390e236/) in a local tmt run, but unsuccessfully -- it works fine. My first instinct was that this runs against cockpit-machines-264 (i.e. what c8s has in its native repos, from cockpit-appstream source) instead of the cockpit-machines-262.gitblablah build from this PR; but the [raw log](https://artifacts.dev.testing-farm.io/246b3cdc-7f7e-46a1-b648-29855390e236//work-all_TYNrs/log.txt) does not confirm that, it does have the correct package version.

The [js.log artifact](https://artifacts.dev.testing-farm.io/246b3cdc-7f7e-46a1-b648-29855390e236//work-all_TYNrs/plans/all/execute/data/test/browser/data/TestMachinesLifecycle-testDelete-centos-8-stream-localhost-22-FAIL.js.log) shows no error  from `domainDelete`.

I added a few more commits for some cleanups and extra debugging. Let's see what that says.

**Comment by martinpitt** [comment]
[Et voilà](https://artifacts.dev.testing-farm.io/3965b145-db2f-4ba4-8bd3-8f377028138a/)! I dropped the hacks. @KKoukiou , @skobyda , as I meddled with this PR quite heavily, do you mind cross-checking my changes?

**Review by martinpitt — APPROVED** [review]

**Review by KKoukiou — COMMENTED** [review]
GH won't allow me to self approve, but checked at the changes and they 're great. thanks for fixing this.

**Comment by martinpitt** [comment]
This [c9s run](https://artifacts.dev.testing-farm.io/6be5db53-b639-47b6-9b66-41dcba1d639f/) corrupted the VM. Let's make sure it's not systematic, retrying. (Everything else green)

**Comment by martinpitt** [comment]
[c9s is kaputt](https://artifacts.dev.testing-farm.io/2c8a3661-d8cf-4245-8c3f-7ffbc49e71cd/), but not due to this PR -- I've seen it in #472 as well [log](https://artifacts.dev.testing-farm.io/a880a31c-cf3b-40b3-b97c-460972cf6178/) -- a puzzle for tomorrow.

**Pull request merged**
