### PR TITLE
Port bootorder dialog to PF4

### PR DESCRIPTION
**Pull request by KKoukiou**
Make use of Draggable list.

See https://github.com/patternfly/patternfly/issues/3712

Blocked on:
* [x] https://github.com/patternfly/patternfly/issues/4138
* [x] https://github.com/patternfly/patternfly-react/issues/5900
* [ ] https://github.com/patternfly/patternfly-react/issues/6317

### CODE REVIEW

**Comment by mvollmer** [comment]
This PR seems to have accidentally reverted the changes to the reference pixels made in #190.

**Review by mvollmer — DISMISSED** [review]
The changes to test/reference should be removed from this PR.

**Review by garrett — CHANGES_REQUESTED** [review]
I like the idea in general, but this is currently unusable.

https://user-images.githubusercontent.com/10246/121147678-60f48880-c841-11eb-8369-fae17c78a25e.mp4

When dragging rows, over anything more than 1 row high, there's an obscene amount of flicker as the component does not know which row should be above.

I recorded this video in 30 FPS; I probably should've recorded it at 60 or 120 FPS, but even at a lower framerate it captures the issue well enough. (It flickers even more than you see here, which is already a nightmare.)

This is not just bad from a UX perspective; it can also trigger motion sickness, migraines, and seizures.

**Comment by KKoukiou** [comment]
> I like the idea in general, but this is currently unusable.
> drag-flicker.mp4
> 
> When dragging rows, over anything more than 1 row high, there's an obscene amount of flicker as the component does not know which row should be above.
> 
> I recorded this video in 30 FPS; I probably should've recorded it at 60 or 120 FPS, but even at a lower framerate it captures the issue well enough. (It flickers even more than you see here, which is already a nightmare.)
> 
> This is not just bad from a UX perspective; it can also trigger motion sickness, migraines, and seizures.

I see what you mean. I can't see the problem upstream so it's something wrong with this specific PR. I will try to identify.

**Comment by garrett** [comment]
> it's something wrong with this specific PR

It seems to happen with the tall lines. I wonder if there's some kind of positioning causing them to be calculated differently for the height? Or if the JS is hacky and makes assumptions that break down?

**Comment by KKoukiou** [comment]
> > it's something wrong with this specific PR
> 
> It seems to happen with the tall lines. I wonder if there's some kind of positioning causing them to be calculated differently for the height? Or if the JS is hacky and makes assumptions that break down?

Hmm the JS is stolen from the website. Same code. So I lean towards that it's something with the content of our rows.

**Comment by garrett** [comment]
If I make the height the same for each row, then it works fine. There's something weird with different sized items. I wonder if this happens when dragging a larger item versus smaller and same sized ones, or if it's only a problem with smaller versus larger?

**Comment by garrett** [comment]
I tested this in-browser just now and found that dragging larger items is fine. So it's when you drag a smaller item around with larger items present. (Others being same or smaller is fine.)

**Comment by KKoukiou** [comment]
> I tested this in-browser just now and found that dragging larger items is fine. So it's when you drag a smaller item around with larger items present. (Others being same or smaller is fine.)

Oh thanks for identidying this. It would  have taken me some hours I bet. Shall we set fixed height?

**Comment by KKoukiou** [comment]
@garrett I don't tihnk inlining the information can be an option here. If you look at the code, https://github.com/cockpit-project/cockpit-machines/blob/fe945e3aa14eff9ba5646818c9090022f170fd10/src/components/vm/overview/bootOrder.jsx#L99 some devices can have really more informtion that three items, and for some these info are not obvious at all, so that we hide the label.

**Comment by garrett** [comment]
I've modified the PF draggable list component example to make one element larger than the others, then tried dragging and hit the same issue we're having here. So this bug is an upstream one.

**Comment by KKoukiou** [comment]
@garrett created upstream issue: https://github.com/patternfly/patternfly/issues/4138

**Comment by KKoukiou** [comment]
This would also be a nice alternative component for this feature: https://github.com/patternfly/patternfly-react/issues/6265

(Since the draggable data list is broken)

**Comment by garrett** [comment]
We'd need to either drop the additional information or have it under each item. Since there's drag and drop here too, it might also suffer from the same issue with variable heights.

I guess the left side would be "Available disks" and the right side would be "Boot disks"? And we'd use a simplified version without filtering? Or the labels could be "Excluded disks" and "Boot disks", which is a bit more contextual and explains that the disks are not used for booting?

**Comment by KKoukiou** [comment]
> We'd need to either drop the additional information or have it under each item. Since there's drag and drop here too, it might also suffer from the same issue with variable heights.
> 
> I guess the left side would be "Available disks" and the right side would be "Boot disks"? And we'd use a simplified version without filtering? Or the labels could be "Excluded disks" and "Boot disks", which is a bit more contextual and explains that the disks are not used for booting?

Generally I agree, just s/disks/devices/ as not only disks are used for booting from but also nics.

**Comment by garrett** [comment]
> Generally I agree, just s/disks/devices/ as not only disks are used for booting from but also nics.

Good point. You're right.

"Excluded devices" "Boot devices", I guess?

**Comment by KKoukiou** [comment]
In favor of https://github.com/cockpit-project/cockpit-machines/pull/512

**Pull request closed without merging**
