### PR TITLE
test: add check for adding existing physical disk device

### PR DESCRIPTION
**Pull request by yunmingyang**

### CODE REVIEW

**Comment by yunmingyang** [comment]
> The new test failed on RHEL-8-5. https://logs.cockpit-project.org/logs/pull-157-20210511-041443-dcdf2fec-rhel-8-5/log.html#45
> Retrying for comparison.

It seems that the VM is out of memory according to the error message, should I modify the parameter of  add_ram_disk and re-push the PR?

**Comment by KKoukiou** [comment]
> > The new test failed on RHEL-8-5. https://logs.cockpit-project.org/logs/pull-157-20210511-041443-dcdf2fec-rhel-8-5/log.html#45
> > Retrying for comparison.
> 
> It seems that the VM is out of memory according to the error message, should I modify the parameter of add_ram_disk and re-push the PR?

You can try but I am not sure this would solve the issue. The add_ram_disk creates a 10MiB pool, and the previous volume takes 1M.

**Comment by KKoukiou** [comment]
Debian stable fails now: error: Failed to create vol sda2
error: internal error: no large enough free extent :'(

**Comment by yunmingyang** [comment]
Let's try 8 for add_ram_disk. I tested locally. It seems to satisfy debian-stable, hope it can also satisfy rhel-8-5

**Comment by KKoukiou** [comment]
> Let's try 8 for add_ram_disk. I tested locally. It seems to satisfy debian-stable, hope it can also satisfy rhel-8-5

Oh you can't download the RHEL images anymore? You need to contact @allisonkarlitskaya for some tokens to do that. lis on IRC.

**Comment by yunmingyang** [comment]
Let's try to use virtual block device. create another ram disk with add_ram_disk will also cause error since there will a check which is "test ! -e /sys/module/scsi_debug"

**Review by KKoukiou — APPROVED** [review]

**Comment by KKoukiou** [comment]
@martinpitt there are a lot of packit failures unrelated to this PR. Are the packit tests having hard time? Can I ignore these?

**Comment by martinpitt** [comment]
The [failure](http://artifacts.dev.testing-farm.io/2ec6fb8f-4d02-4f5a-9208-1bb766892dd3/) in `TestMachinesCreate-testCreateImportDisk` with  `TypeError: y.a.all is not a function` at least seems related -- it's obviously not *caused* by this PR, but it finds a bug. #159 ran 5 days ago and was green, and the Testing Farm is generally happy this week.

As you already retried once, I'd at least be cautious.

**Comment by martinpitt** [comment]
This `y.a.all` crash also [happens a lot](https://logs.cockpit-project.org/logs/pull-2029-20210518-055708-76df68bd-fedora-34-cockpit-project-cockpit-machines/log.html#9-2) in https://github.com/cockpit-project/bots/pull/2029 . So most certainly unrelated, but really a high-profile crash. As packit uses the current cockpit version as opposed to the previously "frozen" one on our image, that may explain the failure pattern here.

**Comment by KKoukiou** [comment]
Ack since this is unrelated to this PR I won't keep this blocked, let's fix the issue separately.

**Pull request merged**
