### PR TITLE
test: Wait for IPv6 address before testing pixels

### PR DESCRIPTION
**Pull request by mvollmer**
So that the picture is stable.

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! Do you have a link to an example failure?

**Comment by mvollmer** [comment]
> Thanks! Do you have a link to an example failure?

Here: https://cockpit-logs.us-east-1.linodeobjects.com/pull-1601-922588b7-20240506-093822-fedora-40/log.html

**Comment by mvollmer** [comment]
(The reference image doesn't have ipv6 in it, so we need to update it. That's why this is Draft.)

**Comment by mvollmer** [comment]
Huh?  Does the IPv6 address actually only show up with `os="linux2022"`? That doesn't make sense to me right now, but...

**Comment by mvollmer** [comment]
> Huh? Does the IPv6 address actually only show up with `os="linux2022"`? That doesn't make sense to me right now, but...

Ah, of course, missing change notifications. We have to wait until there is IPv6 address before switching to the page.

**Comment by mvollmer** [comment]
> > Huh? Does the IPv6 address actually only show up with `os="linux2022"`? That doesn't make sense to me right now, but...
> 
> Ah, of course, missing change notifications. We have to wait until there is a IPv6 address before switching to the page.

Ok, the IPv6 link-local address gets reported by the guest agent, and the agent indeed only gets connected by default with linux2022. So, we only need to do this in #1601.

**Pull request closed without merging**
