### PR TITLE
maintenance updates

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
Is libvirt broken on fedora rawhide?

**Comment by martinpitt** [comment]
@jelly : Yes, this broke a while ago; we didn't fix the two tests or so which started to fail on rawhide, and now it got worse :cry:

**Comment by martinpitt** [comment]
See history on https://github.com/cockpit-project/cockpit-machines/pulls?q=is%3Apr+is%3Aclosed , this broke about 25 days ago.

**Comment by martinpitt** [comment]
[This](http://artifacts.dev.testing-farm.io/f24e9493-9d05-4da6-b9ec-7314e55671ba/) ran 6 days ago and "only" failed `TestMachinesDisks.testAddDiskPool`.

**Comment by martinpitt** [comment]
But you are right, [5 hours ago](http://artifacts.dev.testing-farm.io/aa50177f-3514-4e24-b986-167a401b65ed/)

**Comment by martinpitt** [comment]
OK, this is not a regression -- PR #568 [failed rawhide in the same way](http://artifacts.dev.testing-farm.io/5161f660-1283-436e-ae03-9c9d4862266b/).

**Pull request merged**
