### PR TITLE
Bump cockpit repo commit for fetching lib

### PR DESCRIPTION
**Pull request by KKoukiou**
* [x] blocked by https://github.com/cockpit-project/cockpit/pull/18077

### CODE REVIEW

**Review by jelly — DISMISSED** [review]

**Comment by KKoukiou** [comment]
This is breaking storage volume tests - needs some work

**Review by martinpitt — APPROVED** [review]
Assuming green. Unblocking and triggering tests. Thanks!

**Comment by martinpitt** [comment]
@KKoukiou : Meh, needs pixel updates

**Review by martinpitt — APPROVED** [review]
Danke!

**Pull request merged**
