### PR TITLE
fix race in TestMachinesConsoles.testSerialConsole; drop remaining @no_retry_when_changed

### PR DESCRIPTION
**Pull request by martinpitt**
Let's fix the tests properly if they are still broken.

### CODE REVIEW

**Comment by martinpitt** [comment]
The main failure is `TestMachinesConsoles.testSerialConsole`, which [failed](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-642-20220329-070956-662cceb1-ubuntu-2204/log.html#52) [twice](https://logs.cockpit-project.org/logs/pull-642-20220329-070956-662cceb1-rhel-8-6/log.html#52). The [screenshot](https://logs.cockpit-project.org/logs/pull-642-20220329-070956-662cceb1-rhel-8-6/TestMachinesConsoles-testSerialConsole-rhel-8-6-127.0.0.2-2501-FAIL.png) shows that the VM is not booting at all. This is also our [current top flake](https://logs-https-frontdoor.apps.ocp.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-machines&days=7) (14% failure rate).

According to the weather report, it most often happens on rhel-8-6 (47% failure rate!). However, I can't reproduce this at all locally on rhel-8-6 no fedora-36. I also tried with firefox and headless/interactive browser, but this doesn't look like a browser specific issue -- rather that the VM is somehow mis-defined.

I added another commit to debug this on the infra.

**Comment by martinpitt** [comment]
[This failed run](https://logs.cockpit-project.org/logs/pull-642-20220329-081919-2aac2191-rhel-9-0/log.html#52) proves that the domain *did* boot correctly (see [virsh screenshot](https://logs.cockpit-project.org/logs/pull-642-20220329-081919-2aac2191-rhel-9-0/TestMachinesConsoles-testSerialConsole-vmWithSerialConsole.ppm)), and the XML dump also proves that the domain is correctly defined (`<console type='pty'>`) (I diffed a working and a failing XML).

**Comment by martinpitt** [comment]
Yay! For the record, [statuses on this commit](https://github.com/cockpit-project/cockpit-machines/commit/a7128854af1d13568ea2cf8dcb003b7ff567a70c) are the "stress test" ones, where testSerialConsole ran 8 times. The fedora-35 failures are the "new pixels" due to testSerialConsole{2..7}, and are of course irrelevant. So let's clean this up, and land.

**Comment by martinpitt** [comment]
[c9s failed](https://artifacts.dev.testing-farm.io/230fd0c9-82dd-4de9-b165-4cef822ae5d6/) the same way as in #641. This happened spontaneously again (some recent c9s update). I'll investigate, but let's land this first to avoid PRs fighting with each other's flakes.

**Review by skobyda — APPROVED** [review]

**Pull request merged**
