### PR TITLE
Don't try to translate an empty string

### PR DESCRIPTION
**Pull request by jelly**
Empty msgid's are reserved by GNU gettext.

### CODE REVIEW

**Review by marusak — APPROVED** [review]
Thanks!

**Comment by skobyda** [comment]
The failing pixel tests are unrelated to this PR, as they are present now elsewhere too.
And packit tests seems like they had an "infrastruture" issue? retrying.

**Comment by skobyda** [comment]
\packit

**Comment by skobyda** [comment]
Also the packti test failures are the same as in https://github.com/cockpit-project/cockpit-machines/pull/552, so also unrelated

**Review by skobyda — APPROVED** [review]

**Pull request merged**
