### PR TITLE
Disable "Add" button when attachement is in progress

### PR DESCRIPTION
**Pull request by skobyda**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2129845

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Looks great, thanks!

**Comment by martinpitt** [comment]
@skobyda : When you post a PR, can you please update the bz status like I did in https://bugzilla.redhat.com/show_bug.cgi?id=2129845 ? I.e. set target release, devel_ack+, internal target release, internal target milestone, and status POST. Otherwise we'll have a really hard time with finding the correct bugs when doing the downstream releases. Thanks!

**Review by martinpitt — CHANGES_REQUESTED** [review]
There are pixel test failures: due to adding the `isLoading` button property, they now became wider.

**Review by marusak — APPROVED** [review]
Thank you!

**Pull request merged**
