### PR TITLE
node_modules: Update chrome-remote-interface for chromium 111

### PR DESCRIPTION
**Pull request by martinpitt**
Stolen from @jelly's cockpit commit.

### CODE REVIEW

**Comment by jelly** [comment]
Rawhide fails, I am assuming this is a new issue and being unrelated to the `package.json` changes I'll merge it.

```
not ok 13 /var/ARTIFACTS/work-storagerncdzvon/plans/all/storage/discover/default-0/tests/test/check-machines-storage-pools TestMachinesStoragePools.testStoragePoolsCreate [ND@-1] # RETRY 1 (be robust against unstable tests)
```

```
# Result testStorageVolumesCreate (__main__.TestMachinesStoragePools.testStorageVolumesCreate) failed
# 1 TEST FAILED [38s on ip-172-31-27-7]
```

@skobyda are you aware of these issues?

**Review by jelly — APPROVED** [review]

**Comment by skobyda** [comment]
`subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '22', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', 'localhost', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-41520', 'set -e;', 'wipefs -a /dev/sda; pvcreate /dev/sda; vgcreate vol_grp1 /dev/sda']' returned non-zero exit status 5.`

@jelly yup that's a known flake, unrelated to this PR

**Comment by jelly** [comment]
> `subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '22', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', 'localhost', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-41520', 'set -e;', 'wipefs -a /dev/sda; pvcreate /dev/sda; vgcreate vol_grp1 /dev/sda']' returned non-zero exit status 5.`
> 
> @jelly yup that's a known flake, unrelated to this PR

Ah thanks! I wasn't sure if it was a flake or a new issue in rawhide.

**Comment by martinpitt** [comment]
It's not a flake -- it has failed consistently in the last two or so weeks, it's a rawhide regression that still needs to be debugged and reported.

**Pull request merged**
