### PR TITLE
Use 'type' instead of 'which' which is standard unix

### PR DESCRIPTION
**Pull request by KKoukiou**
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2196701

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Right, `type` or `command`. Thanks for figuring this out! I'm glad it was something "easy" after all.

**Comment by KKoukiou** [comment]
There is a problem with ubuntu, debian, arch, will check it tomorrow.

**Comment by jelly** [comment]
> There is a problem with ubuntu, debian, arch, will check it tomorrow.

Well type does not really exists as binary right, it's a shell buildin. So you should probaly use `cockpit.shell` instead of spawn or `/bin/sh -c`?

It works on Fedora because that has `/usr/bin/type`

/usr/bin/type: a /usr/bin/sh script, ASCII text executable

**Comment by martinpitt** [comment]
Ah yes -- cockpit.shell() sounds good then. `virt-install --version` would also work, but as it's Python, that's a lot more expensive.

**Review by martinpitt — APPROVED** [review]
Danke!

**Pull request merged**
