### PR TITLE
package.json: Update @patternfly/react-console

### PR DESCRIPTION
**Pull request by cockpituous**

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "@patternfly/react-console": "4.6.0",
src/components/vm/consoles/consoles.jsx:import { AccessConsoles } from "@patternfly/react-console";
src/components/vm/consoles/desktopConsole.jsx:import { DesktopViewer } from '@patternfly/react-console';
src/components/vm/consoles/vnc.jsx:import { VncConsole } from '@patternfly/react-console';
```

**Comment by martinpitt** [comment]
The build failed on some transient npm error, I [restarted the workflow](https://github.com/cockpit-project/cockpit-machines/actions/runs/769209231).

**Review by martinpitt — APPROVED** [review]
Tested visually, no difference to the previous version.

**Pull request merged**
