### PR TITLE
pyproject: adjust to new ruff settings layout

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**

### CODE REVIEW

**Comment by mvollmer** [comment]
The pixel change looks lie its too much: There is a whole new "Changes pending" annotation at the top, among other things.

**Comment by mvollmer** [comment]
> The pixel change looks like its too much: There is a whole new "Changes pending" annotation at the top, among other things.

Yeah, CI agrees: https://cockpit-logs.us-east-1.linodeobjects.com/pull-1422-20240205-154004-1147f268-fedora-39/pixeldiff.html#TestMachinesLifecycle-testBasic-vm-details

**Comment by allisonkarlitskaya** [comment]
> > The pixel change looks like its too much: There is a whole new "Changes pending" annotation at the top, among other things.
> 
> Yeah, CI agrees: https://cockpit-logs.us-east-1.linodeobjects.com/pull-1422-20240205-154004-1147f268-fedora-39/pixeldiff.html#TestMachinesLifecycle-testBasic-vm-details

I'll put it back then.  It must have been a flake.

**Review by martinpitt — APPROVED** [review]
Thanks! This is urgent.

**Comment by martinpitt** [comment]
[This virtiofsd crash](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1422-20240205-160053-e22bb0ed-fedora-39/log.html#73) has been on the pilot board for a few weeks, can be ignored.

[This bridge crash](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1422-20240205-160056-e22bb0ed-ubuntu-stable/log.html#85) is also ancient, can be ignored here.

**Pull request merged**
