### PR TITLE
packit: Run tests on CentOS 9 stream

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
[c9s failures](http://artifacts.dev.testing-farm.io/5bc31a20-e616-4911-af47-d0912c8026c1/): `TestMachinesCreate.testCreateUrlSource` is a known issue, this needs a naughty symlink. I sent https://github.com/cockpit-project/bots/pull/2634 for that.

`TestMachinesCreate.testConfigureBeforeInstall` was a missing special case.

The [c8s](https://github.com/cockpit-project/cockpit-machines/pull/452/checks?check_run_id=4225691223) and [rawhide](https://github.com/cockpit-project/cockpit-machines/pull/452/checks?check_run_id=4226141060) failures are unrelated -- the test just stops in the middle without an error message. I asked OSCI.

**Comment by martinpitt** [comment]
[success](https://github.com/cockpit-project/cockpit-machines/pull/452/checks)! Pushed a few cleanups, and trying again.

**Comment by martinpitt** [comment]
I understand the [c8s failure](http://artifacts.dev.testing-farm.io/4c9d5e09-adc0-4eed-bde0-875d8ba05d51/) now: c8s moved to libvirt-daemon-7.9.0-1.module_el8.6.0+983+a7505f3f.x86_64 now, which does support the feature. But the test is written in a racy way, and does not wait until the page is built up sufficiently - so it catches it at a state when the feature detection is not complete yet. So:

 * Fix the test to wait for something else to appear first
 * drop centos-8-stream from the condition list for the "OSes that don't support that feature"
 * refresh our centos-8-stream image to pick up the new version

**Comment by martinpitt** [comment]
The packit c8s failure is handled in #455, and rawhide is unrelated. So I believe this is ready to land.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
