### PR TITLE
test: add test skips for newly introduced rhel-9-3 image

### PR DESCRIPTION
**Pull request by KKoukiou**
Needed for https://github.com/cockpit-project/bots/pull/4565

### CODE REVIEW

**Comment by KKoukiou** [comment]
Hmm I am not able to trigger the tests: 

```
[kkoukiou@sequioa cockpit-machines]$ bots/tests-trigger -f 990 rhel-9-3 --bots-pr 4565
rhel-9-3@bots#4565: triggering on pull request 990
```
But nothing happens here.

**Comment by martinpitt** [comment]
@KKoukiou You need to teach the bots about that context by adding `_manual` (pseudo-)branch contexts to testmap.

**Review by martinpitt — APPROVED** [review]
Anyway, this looks good -- it's completely harmless for the existing contexts.

Note that testlib supports globs now, so you could rewrite all of these to `rhel-8*`, `rhel-9-*`, or in the appropriate cases even just `rhel-*`.

**Comment by martinpitt** [comment]
Let's keep this simple -- land this, and test against https://github.com/cockpit-project/bots/pull/4565

**Pull request merged**
