### PR TITLE
DONTMERGE: (Failing pixel-test version)Test testlib fix with eliminated dataclass

### PR DESCRIPTION
**Pull request by KKoukiou**
This tests the change in cockpit-project/cockpit#15825
but as cockpit itself does not use pixel testing yet, we need to test it
in this project.

### CODE REVIEW

**Comment by KKoukiou** [comment]
Weird, this should not have succeeded.

**Comment by KKoukiou** [comment]
Seems pixel tests dont work even with cockpit 244 tag, https://github.com/cockpit-project/cockpit-machines/pull/168

**Comment by martinpitt** [comment]
Hmm, but #168 did fail as expected, so somehow my PR is bad.

**Comment by martinpitt** [comment]
lol -- we only test pixels on TEST_OS_DEFAULT, which is Fedora **34** now. The [f-33 test in #168](https://logs.cockpit-project.org/logs/pull-168-20210512-174539-af123c98-fedora-33/log.html) did *not* fail because of pixels, but due to a flaky test. Only the [f-34 test](https://logs.cockpit-project.org/logs/pull-168-20210512-172605-af123c98-fedora-34/log.html) failed due to pixels. Locally, the test fails for me on f34.

Hence, triggering f34 test here.

**Comment by martinpitt** [comment]
And lo and behold, it [failed](https://logs.cockpit-project.org/logs/pull-167-20210513-053609-2d82150b-fedora-34/log.html#51).

Closing, this fulfilled its purpose.

**Pull request closed without merging**
