### PR TITLE
packit: add Fedora 38 testing and release, drop Fedora 36

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by jelly** [comment]
Both rawhide and F38 fail on a known naughty https://github.com/cockpit-project/bots/issues/4308

**Comment by jelly** [comment]
This should fix it https://github.com/cockpit-project/bots/pull/4404

**Comment by martinpitt** [comment]
I landed the bots PR and retried the two failing packit tests. However, that should at most fix fedora-rawhide,  fedora-38 already ought to have worked before -- at least the bots PR didn't change fedora-38 naughties.

**Comment by martinpitt** [comment]
Hmm, curious -- this is read from /etc/os-release. I suppose Fedora 38 did not yet get a specific upload for setting ID to "38" then?

**Comment by martinpitt** [comment]
There's a high chance that this will go green, so I triggered the required d-testing

**Comment by jelly** [comment]
> There's a high chance that this will go green, so I triggered the required d-testing

And it did \o/

**Pull request merged**
