### PR TITLE
test: add a check about disk bus if creating a VM without OS

### PR DESCRIPTION
**Pull request by yunmingyang**

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! But `TestMachinesDisks.testDiskEdit` fails everywhere now.

**Comment by yunmingyang** [comment]
Let me check it, thanks a lot

**Comment by jelly** [comment]
Re-triggered the tests, let's see if they get green.

**Review by martinpitt — APPROVED** [review]
Thanks! Also for the f-stringification in machineslib.py.

**Pull request merged**
