### PR TITLE
test: Drop some unused constants and methods; pyproject: Add vulture suppressions

### PR DESCRIPTION
**Pull request by martinpitt**
See [current failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6048-20240311-125835-b465e9b2-ubuntu-stable-cockpit-project-cockpit-machines/log.html) after today's rollout of a  new tasks container. Plus, testing from bots doesn't currently respect `.cockpit-ci/container` (fixing that is high on the pilot board!)

### CODE REVIEW

**Comment by martinpitt** [comment]
Hmm, [that failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1488-1666785f-20240311-143309-fedora-40/log.html) is unexpected. This is a PR in machines itself, it ought to run in the old quay.io/cockpit/tasks:2024-03-05, not in :latest. But that container is missing in the Job output. Investigating..

**Comment by martinpitt** [comment]
PR #1489 *did* use the correct container. That was a branch from origin, not a fork. I bet that's the significant difference.

**Review by allisonkarlitskaya — APPROVED** [review]

**Comment by allisonkarlitskaya** [comment]
+1 for the changes, except that they seem to have introduced a lot of red...

**Comment by martinpitt** [comment]
Re-posted as PR #1491 as origin branch, this is urgent and blocks too much.

**Comment by martinpitt** [comment]
Meh, that didn't actually work either ... https://cockpit-logs.us-east-1.linodeobjects.com/pull-1491-ca96a49c-20240312-101647-arch/log.html

**Comment by martinpitt** [comment]
It did work, I just didn't change the SHA, so old statuses.

**Pull request closed without merging**
