### PR TITLE
package.json: Update @patternfly/react-console

### PR DESCRIPTION
**Pull request by cockpituous**

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "@patternfly/react-console": "4.3.31",
src/components/vm/consoles/consoles.jsx:import { AccessConsoles } from "@patternfly/react-console";
src/components/vm/consoles/desktopConsole.jsx:import { DesktopViewer } from '@patternfly/react-console';
src/components/vm/consoles/vnc.jsx:import { VncConsole } from '@patternfly/react-console';
```

**Comment by KKoukiou** [comment]
The selector's style seems broken, but this also is on master. 
Screen Shot 2021-04-13 at 09 08 22

docs for react-console has dissapeared as well https://github.com/patternfly/patternfly-react/issues/5649

This needs a bit attention.

**Comment by martinpitt** [comment]
@KKoukiou : Confirmed, I get the same on master. The "VNC console" does not have a button-like frame around it. The dropdown works okay, though:

image

**Comment by KKoukiou** [comment]
So the missing borders are addressed by https://github.com/cockpit-project/cockpit-machines/pull/91 . 

This looks good otherwise.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
