### PR TITLE
packaging: add virtiofsd dependency for fedora-39

### PR DESCRIPTION
**Pull request by tomasmatus**

### CODE REVIEW

**Comment by tomasmatus** [comment]
So this probably isn't the right way of doing it but I believe it has to be added here somehow 😄

**Review by martinpitt — CHANGES_REQUESTED** [review]
That looks wrong -- c-machines is supposed to work without virtiofsd, that's why it's only a suggests, not a requires. The *tests* assume that it's installed, to test device passthrough.

**Comment by tomasmatus** [comment]
ah I see so does that mean this can stay unchanged?

**Comment by martinpitt** [comment]
Yes, I think so.

**Comment by tomasmatus** [comment]
Closing then. As change isn't needed

**Pull request closed without merging**
