### PR TITLE
test: Avoid alternative truths, fix libvirt resource cleanup

### PR DESCRIPTION
**Pull request by martinpitt**
These days we often get a [mess like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1419-20240203-101153-37c84643-fedora-39-firefox/log.html) or [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1419-20240203-101153-37c84643-debian-stable/log.html). This should help a lot to pinpoint the offenders.

 - [x] builds on top of PR #1419
 - [x] [real race condition](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1420-20240203-150412-f6f2d772-fedora-39/log.html#26-2): VM goes away during iteration

### CODE REVIEW

**Comment by martinpitt** [comment]
Fantastisch! This run only had a few totally unrelated flakes, like [this pybridge error](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1420-20240203-195852-eea5f13f-ubuntu-stable/log.html) and the usual "chromium OOM" hangs, but no "mass failure" or cleanup troubles at all! :star: I'll do a no-change force-push to run the whole lot again, to gain some confidence.

**Comment by martinpitt** [comment]
Works! I've seen [this flake twice](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1420-20240203-203840-0e318fdc-ubuntu-2204/log.html#84) which feels simple, I'll add a fix.

**Comment by martinpitt** [comment]
OK, [this patch](https://github.com/cockpit-project/cockpit-machines/pull/1420/commits/009b1b0e2e16c237cf5e5e9c0372f5f9287898f3) [didn't help](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1420-20240203-211706-009b1b0e-ubuntu-2204/log.html#84). Darn, it'd have been so nice and obvious. I back it out and leave that for another day.

**Review by jelly — APPROVED** [review]
Thanks, that was some serious cleanup work :exploding_head:

**Pull request merged**
