### PR TITLE
test: Ignore storage and memory helpers in dialog pixel tests

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
That's beatiful. Did not know there was option for ignoring alredy. I look forward to see how the comparison looks now.

**Comment by martinpitt** [comment]
Niiiice! Great work @mvollmer !

**Comment by mvollmer** [comment]
Let's run fedora-33 again, for the @dataclass version of assert_pixels.

**Comment by mvollmer** [comment]
And again, with ignoring of very small differences in RGB values.

**Comment by mvollmer** [comment]
> And again, with ignoring of very small differences in RGB values.

And again, because I forgot to push in the other repo.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
