### PR TITLE
package.json: Update date-fns, adjust pixel tests for Chromium 93 update

### PR DESCRIPTION
**Pull request by cockpituous**

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "date-fns": "2.24.0",
src/helpers.js:import * as dfnlocales from 'date-fns/locale';
src/helpers.js:import { formatRelative } from 'date-fns';
```

**Comment by martinpitt** [comment]
The failed pixel tests are due to the recent chromium update, similar to https://github.com/cockpit-project/cockpit/pull/16363

**Comment by martinpitt** [comment]
packit on rawhide [failed](http://artifacts.dev.testing-farm.io/8eaa7580-bbbd-43c3-8e38-e5015d805f9c/) because chromium broke:

    /usr/bin/chromium-browser: symbol lookup error: /usr/bin/chromium-browser: undefined symbol: hb_subset_input_set_drop_hints

I'll report this to bugzilla, but that doesn't need to block this PR.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
