### PR TITLE
Fix Fedora 40 fmf test

### PR DESCRIPTION
**Pull request by martinpitt**
See the [recent](https://artifacts.dev.testing-farm.io/4f4438ff-ae10-4fd2-84b8-556bd608f75a/) [failures](https://artifacts.dev.testing-farm.io/b6cf6bbe-c859-4149-a96f-0254c7505d4c/) in Fedora 40.

### CODE REVIEW

**Comment by martinpitt** [comment]
Oh, that actually helped -- I totally expected a failure on c8s, but apparently the package exists. But [now it fails differently](https://artifacts.dev.testing-farm.io/5d5ed7a0-288e-49cd-b293-aef0d0769044/):
```
error: Failed to open file '/etc/libvirt/qemu/networks/default.xml': No such file or directory
```

But wait, this makes no sense -- our spec already has
```
Requires: (libvirt-daemon-driver-interface if virt-install)
Requires: (libvirt-daemon-config-network if virt-install)
```
and indeed we don't test-depend on `virt-install`, we just `Recommend` it. That *should* be installed by default, though!?

**Comment by martinpitt** [comment]
I tried to reproduce that in `podman run -it --rm fedora:40`:
```
dnf install --allowerasing https://download.copr.fedorainfracloud.org/results/packit/cockpit-project-cockpit-machines-1528/fedora-40-x86_64/07252647-cockpit-machines/cockpit-machines-310-1.20240403060431800072.pr1528.5.gffb7e54.fc40.noarch.rpm
```

This *does* install `virt-install`. Of course the TF run does a lot of other things, but they don't seem particularly relevant/influencing. Well, I'll let the current run finish, triple-check that `virt-install` is missing, and then add it as an explicit test dependency.

**Comment by martinpitt** [comment]
[confirmed](https://artifacts.dev.testing-farm.io/4c1007ed-c379-4f59-9816-8823f692a83c/), no virt-install, and for some weird reason [dnf does not want to install the Recommends:](https://artifacts.dev.testing-farm.io/4c1007ed-c379-4f59-9816-8823f692a83c/guest-setup-4ccbb53f-89a2-49ae-8783-340822640284/artifact-installation-4ccbb53f-89a2-49ae-8783-340822640284/4-Install-packages.txt).

**Comment by martinpitt** [comment]
Works! OK, let's clean up and push the real thing.

**Review by jelly — APPROVED** [review]

**Pull request merged**
