### PR TITLE
test: Disable SELinux when RHEL-49567 is present

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
This makes centos-10 pretty green.

**Review by martinpitt — APPROVED** [review]
Thanks!

**Comment by mvollmer** [comment]
Uff, breaks on non-rpm systems of course.

**Comment by mvollmer** [comment]
> Uff, breaks on non-rpm systems of course.

Actually, it doesn't... :-/

**Comment by mvollmer** [comment]
This has now reproduced the TestMachinesCreate.testCreateDownloadAnOS failure that we see on TF in our own CI.

**Pull request merged**
