### PR TITLE
Makefile: update to test/common without expect_load

### PR DESCRIPTION
**Pull request by mvollmer**
No changes are necessary to the tests themselves.

### CODE REVIEW

**Comment by martinpitt** [comment]
That [cloudBase failure](https://logs.cockpit-project.org/logs/pull-586-20220222-075721-7961b8b3-fedora-35/log.html) is suspicious -- I already saw it in the draft PR yesterday, and it's not normally that brittle. It might not be related to expect_load changes, but perhaps we changed something else in testlib?

**Comment by martinpitt** [comment]
Notes: Very likely related to using the new test scheduler with higher parallelization. Worth trying if it reproduces to run these tests in that order in a ./vm-run machine:

```
❱❱❱ curl -sk https://logs.cockpit-project.org/logs/pull-586-20220222-075721-7961b8b3-fedora-35/log | grep ND@0
ok 72 /work/bots/make-checkout-workdir/test/check-machines-storage-pools TestMachinesStoragePools.testStorageVolumesCreate [ND@0]
ok 66 /work/bots/make-checkout-workdir/test/check-machines-settings TestMachinesSettings.testVCPU [ND@0]
ok 54 /work/bots/make-checkout-workdir/test/check-machines-networks TestMachinesNetworks.testNetworks [ND@0]
ok 60 /work/bots/make-checkout-workdir/test/check-machines-nics TestMachinesNICs.testVmNICs [ND@0]
ok 38 /work/bots/make-checkout-workdir/test/check-machines-lifecycle TestMachinesLifecycle.testLibvirt [ND@0] # SKIP Known issue #2898
ok 31 /work/bots/make-checkout-workdir/test/check-machines-hostdevs TestMachinesHostDevs.testHostDevicesList [ND@0]
ok 26 /work/bots/make-checkout-workdir/test/check-machines-filesystems TestMachinesFilesystems.testBasicSessionConnection [ND@0]
ok 21 /work/bots/make-checkout-workdir/test/check-machines-disks TestMachinesDisks.testAddDiskPool [ND@0]
ok 15 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testCreateUrlSource [ND@0]
not ok 9 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testCreateCloudBaseImage [ND@0] # RETRY 1 (be robust against unstable tests)
```

**Comment by mvollmer** [comment]
> That [cloudBase failure](https://logs.cockpit-project.org/logs/pull-586-20220222-075721-7961b8b3-fedora-35/log.html) is suspicious

I can reproduce it locally, but only rarely.  It fails all by itself. It looks like we destroy the machine while vm-install is still busy with it and this somehow leads to the page being stuck in "Running". Interrupting vm-install should be legal, so the page getting stuck might be the problem.

**Comment by mvollmer** [comment]
> so the page getting stuck might be the problem.

No, the test was (likely) executing the "virsh destroy" at just the wrong time.  When the test failed, the domain was really still running, and the page was correct.

**Comment by martinpitt** [comment]
Ugh, now this is running into the "3x retry" trap. We still have a lot of other flakes here..

**Review by martinpitt — APPROVED** [review]
Thank you! (still waiting for packit rawhide)

**Pull request merged**
