### PR TITLE
DBG - Amplify TestMachinesLifecycle.testBasic

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
First run all green... hmm.

**Comment by martinpitt** [comment]
[This is the failure](https://artifacts.dev.testing-farm.io/a350f7e8-285f-459f-b5a5-100184df3416/). The text output and [screenshot](https://artifacts.dev.testing-farm.io/a350f7e8-285f-459f-b5a5-100184df3416/work-basicwi1e4obs/plans/all/basic/execute/data/guest/default-0/test/browser/basic-1/data/TestMachinesLifecycle-testBasic-centos-9-stream-localhost-22-FAIL.png) both have it as "Running", so either the `virsh suspend subVmTest1` failed silently, or it takes an awful lot of time, or (most probably explanation), the UI didn't get the event?

**Comment by mvollmer** [comment]
It fails on TF, but not in our CI: https://artifacts.dev.testing-farm.io/ee6ad14d-5e50-4796-ab46-33f4e8b9a3e7/

**Comment by martinpitt** [comment]
@mvollmer Hint: add `b.eval_js('window.debugging = "machines"')` and `b.cdp.trace = True` to that test, and let's look at the received events?

**Comment by mvollmer** [comment]
Now TMTF is green as well...

**Comment by mvollmer** [comment]
I'll run this again...

**Comment by mvollmer** [comment]
> I'll run this again...

Still all green.

I'll run it again with all tests enabled, maybe there is cross chatter.

**Comment by mvollmer** [comment]
> > I'll run this again...
> 
> Still all green.
> 
> I'll run it again with all tests enabled, maybe there is cross chatter.

Green again. Let's run our own CI as well.

**Comment by martinpitt** [comment]
Just saw it again in #1516 in [this log](https://artifacts.dev.testing-farm.io/428ba372-b761-4dd0-ae39-97407f47f7b7/)

**Comment by martinpitt** [comment]
Nice, [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1512-a7438871-20240325-090429-fedora-39-devel/log.html#90-1) seems to be the same -- so it happens on our infra as well.

**Pull request closed without merging**
