### PR TITLE
Some `Add disk` dialog fixes

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
This makes some pixel tests crazy - and therefore they need some adjustment - but other than that the code is ready for review.

**Comment by martinpitt** [comment]
The [testAddDiskPool](https://logs.cockpit-project.org/logs/pull-296-20210730-173407-f63bf8dc-fedora-34/log.html#59) changed pixels are really evil -- not only does the "Add button" sometimes get a bit larger, but it also captures the text cursor in the "Size" field. Sometimes it's visible, sometimes not. We first need to move the focus to a field without the cursor to pin this down.

**Comment by martinpitt** [comment]
The [testAddDiskPool](https://logs.cockpit-project.org/logs/pull-296-20210730-173407-f63bf8dc-fedora-34/log.html#59) changed pixels are really evil -- not only does the "Add button" sometimes get a bit larger, but it also captures the text cursor in the "Size" field. Sometimes it's visible, sometimes not. We first need to move the focus to a field without the cursor to pin this down.

**Comment by marusak** [comment]
>  We first need to move the focus to a field without the cursor to pin this down.

`b.blur("<selector for the 'Size' field>")` should do, shouldn't it?

**Comment by martinpitt** [comment]
I updated the pixel tests to avoid the cursor in #302 ,  so let's try this again here.

**Comment by martinpitt** [comment]
OK, seems we *have* to get down to the bottom of this weird "Add" button size change.. it's not predictable right now.

**Comment by martinpitt** [comment]
I sent PR #303 to land the two simple fixes. I rebased this PR. The first commit is the one that introduces the dialog instability, so keeping as draft until this gets debugged.

**Comment by KKoukiou** [comment]
Sorry for the ignore selector, I really was not able to figure out how to stabilize them :(

**Comment by martinpitt** [comment]
@KKoukiou : Pragmatic solution, let's not block this fix indeed. Thanks!

**Comment by marusak** [comment]
Needs rebase. I can take a look in the evening.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
