### PR TITLE
Disable choosing write access when editing cdrom devices

### PR DESCRIPTION
**Pull request by KKoukiou**
See https://gitlab.com/libvirt/libvirt/-/issues/209

### CODE REVIEW

**Comment by KKoukiou** [comment]
Please fix the commit message (remove for) if you merge it.

**Review by martinpitt — DISMISSED** [review]
Test would be nice, but the fix makes sense. Thanks!

**Comment by KKoukiou** [comment]
> Test would be nice, but the fix makes sense. Thanks!

Added some checks in the test.

**Review by martinpitt — APPROVED** [review]
Nice, thanks!

**Comment by martinpitt** [comment]
[firefox test passed](https://logs.cockpit-project.org/logs/pull-341-20210901-085349-7c22a68a-fedora-34-firefox/log.html), just wasn't marked as such in GitHub. Landing.

**Pull request merged**
