### PR TITLE
Hash passwords provided by the user for cloud base image

### PR DESCRIPTION
**Pull request by skobyda**
This will allow us to safely store user-data file in the system, and thus allow "Cloud base image" + "Create and edit" options together.

### CODE REVIEW

**Comment by jelly** [comment]
Unrelated, but can this approach also resolve https://github.com/cockpit-project/cockpit-machines/issues/920

**Comment by KKoukiou** [comment]
mkpasswd does not exist on ach, centos-8, debians, rhel and ubuntu. Essentially it's just available on fedora.

**Comment by skobyda** [comment]
Those two failing packing tests seems like unrelated flakes. @KKoukiou Mind giving a re-review? 
In the end, I decided to use openssl CLI tool to generate hash instead of python's crypt/haslib. The reason is it was more straighforward, uses its own defaults for length and generating random salt (in python we would have to specify all of tha tourself, generate our own random salt number of corrent length...) and already produces the hash in a format of /etc/shadow: `$6$[salt]$[hash]`. In python, we would have to format it ouserls.

**Review by KKoukiou — APPROVED** [review]

**Comment by skobyda** [comment]
Tests all green, thanks for review

**Pull request merged**
